### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by woodyrew** [metalsmith/drafts#4]
@f2prateek could you get TravisCI added to this repo please?

Thanks, Woody

**Comment by f2prateek** [comment]
hey @woodyrew  - i've activated travis CI! I think you may need a custom .travis.yml file if the default doesn't work though.

**Comment by ghost** [comment]
Dude, is there a record for quickest resolved issue? This might be it 😋

**Comment by woodyrew** [comment]
Thanks Prateek :)
